- name: Initiation Kubernetes cluster
  hosts: all
  become: true

  tasks:

  - name: Run kubeadm init command
    shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-advertise-address {{ ip }}
    run_once: true

  - name: Set KUBECONFIG environment variable
    environment:
      KUBECONFIG: "/etc/kubernetes/admin.conf"

  - name: Generate join command token
    shell: kubeadm token create --print-join-command
    register: join_command
    run_once: true

  - name: Execute join command on all hosts except the first one
    shell: "{{ join_command.stdout }}"
    when: inventory_hostname != groups['all'][0]

  - name: Apply Flannel network plugin 
    shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
    run_once: true

  - name: Run kubeadm completion  
    command: kubeadm completion bash
    register: kubeadm_completion_output
    

  - name: Write kubeadm completion output to file
    copy:
      content: "{{ kubeadm_completion_output.stdout }}"
      dest: /etc/bash_completion.d/kubeadm
   
  
  - name: Run kubectl completion  
    command: kubectl completion bash
    register: kubectl_completion_output
    

  - name: Write kubectl completion output to file
    copy:
      content: "{{ kubectl_completion_output.stdout }}"
      dest: /etc/bash_completion.d/kubectl
  
  - name: Source kubeadm and kubectl bash completion
    command: "source /etc/bash_completion.d/{{ item }}"
    loop:
      - kubeadm
      - kubectl
  